apiVersion: v1
kind: Service
metadata:
  name: oracle-db-service
  namespace: oracle
  labels:
    app: oracle-db
spec:
  type: NodePort
  selector:
    app: oracle-db
  ports:
  - port: 1521
    targetPort: 1521
    nodePort: 30521
    name: oracle
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    name: em
---
apiVersion: v1
kind: Service
metadata:
  name: oracle-db-lb
  namespace: oracle
  labels:
    app: oracle-db
spec:
  type: LoadBalancer
  selector:
    app: oracle-db
  ports:
  - port: 1521
    targetPort: 1521
    name: oracle
  - port: 8080
    targetPort: 8080
    name: em