apiVersion: v1
kind: Service
metadata:
  name: oracle-db-headless
  namespace: oracle
  labels:
    app: oracle-db
spec:
  ports:
  - port: 1521
    name: oracle
  - port: 8080
    name: em
  clusterIP: None
  selector:
    app: oracle-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oracle-db
  namespace: oracle
spec:
  serviceName: oracle-db-headless
  replicas: 1
  selector:
    matchLabels:
      app: oracle-db
  template:
    metadata:
      labels:
        app: oracle-db
    spec:
      containers:
      - name: oracle
        securityContext:
          privileged: true
        image: absolutapps/oracle-12c-ee:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1521
          name: oracle
        - containerPort: 8080
          name: em
        env:
        - name: ORACLE_SID
          value: "ORCL"
        - name: SERVICE_NAME
          value: "ORCL"
        - name: INIT_MEM_PST
          value: "40"
        volumeMounts:
        - name: oracle-data
          mountPath: /u01/app/oracle
        - name: init-scripts
          mountPath: /oracle.init.d
      volumes:
      - name: init-scripts
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: oracle-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "nfs-client"
      resources:
        requests:
          storage: 20Gi