apiVersion: v1
kind: Service
metadata:
  name: oracle-db-headless
  namespace: oracle
  labels:
    app: oracle-db
spec:
  ports:
  - port: 1521
    name: oracle
  - port: 5500
    name: em
  clusterIP: None
  selector:
    app: oracle-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oracle-db
  namespace: oracle
spec:
  serviceName: oracle-db-headless
  replicas: 1
  selector:
    matchLabels:
      app: oracle-db
  template:
    metadata:
      labels:
        app: oracle-db
    spec:
      containers:
      - name: oracle
        image: absolutapps/oracle-12c-ee:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1521
          name: oracle
        - containerPort: 5500
          name: em
        env:
        - name: ORACLE_SID
          value: "ORCLCDB"
        - name: ORACLE_PDB
          value: "ORCLPDB1"
        - name: ORACLE_PWD
          value: "Oracle123"
        - name: ORACLE_CHARACTERSET
          value: "AL32UTF8"
        volumeMounts:
        - name: oracle-data
          mountPath: /opt/oracle/oradata
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
  volumeClaimTemplates:
  - metadata:
      name: oracle-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "nfs-client"
      resources:
        requests:
          storage: 20Gi